function [aero,initialization] = soccer_ball()
    
    
    %% American Football Aerodynamic and Inertial Properties
    % This file defines the physical constants and aerodynamic coefficient
    % functions required for a 6-Degrees-of-Freedom (6DoF) simulation of an
    % American Football (based on the "long bomb" parameters from a paper).
    % The origin of the body frame is set at the Center of Gravity (CoG).
    % X-axis: along the long axis (spin axis), positive towards the nose.
    % Y-axis: out the side. Z-axis: down (assuming a level throw).
    
    % --- 1. Physical Dimensions and Mass Properties ---
    
    % Physical Dimensions (based on regulation size, averages)
    L_major_axis = 0.28;        % Major axis length (tip-to-tip) [m]
    D_max_diameter = 0.17;      % Maximum diameter [m]
    
    % Mass and Inertia (approximated for a 0.400 kg prolate spheroid)
    aero.m = 0.400;             % Mass [kg]
    
    % Inertia Matrix (I_total in body frame [kg*m^2])
    % UPDATED: Values based on paper (Il = 1.94e-3, It = 3.21e-3)
    I_roll  = 0.00194;          % Ixx (Longitudinal MOI, along the spin axis)
    I_pitch = 0.00321;          % Iyy (Transverse MOI)
    I_yaw   = 0.00321;          % Izz (Transverse MOI)
    aero.I = diag([I_roll, I_pitch, I_yaw]);
    
    % Center of Gravity (CoG) location
    % A well-balanced football has its CoG at the geometric center.
    aero.CoG = [0; 0; 0];       % CoG is at the body origin (center)
    aero.percentage_CoG = 0.5;  % 50% of L_major_axis
    
    % Reference Dimensions for Aerodynamics
    aero.L = L_major_axis;      % Major length (used for moment calculations)
    aero.D = D_max_diameter;    % Max diameter
    aero.S = (pi/4) * aero.D^2; % Reference Area: Max cross-sectional area [m^2]
    aero.aspect_ratio = aero.L / aero.D; % approx 1.65
    
    aero.b = D_max_diameter;     % span = diameter
    aero.c = L_major_axis;       % chord = distance from LE to TE
    
    % Atmospheric and Environmental
    aero.rho = 1.225;           % Air density at sea level [kg/m^3]
    aero.g = 9.81;              % Gravity [m/s^2]
    aero.V_wind_i = [0; 0; 0];  % Initial wind vector [m/s]
    
    % --- 2. Aerodynamic Centers and Offsets ---
    
    % Center of Pressure (CoP) relative to CoG:
    % For a symmetric, non-spinning prolate spheroid, the CoP is slightly
    % forward of the CoG (i.e., nose-heavy stability).
    % A small offset is required for stability (Cm_alpha must be negative).
    % Let's assume CoP is 0.01m (1cm) forward of CoG.
    aero.r_offset = [0.01; 0; 0]; % Center of Pressure location [m] relative to CoG
    
    % --- 3. Placeholder Polynomial Coefficients ---
    % These are highly simplified placeholders. Real data depends heavily on
    % stitching and surface texture.
    
    % p_CD: Drag coefficients (Coefficients for polyval(p, alpha))
    % Drag is mostly constant and increases slightly with angle of attack (alpha)
    p_CD = [0.005, 0.4]; % Example: CD = 0.4 + 0.005*alpha (where alpha is in degrees, but function is set up for rad below)
    
    % p_CL: Lift coefficients
    % Lift is roughly linear with alpha up to 10 degrees.
    p_CL = [0.8, 0]; % Example: CL = 0.8 * alpha (where alpha is in radians)
    
    % p_Cm: Static Pitching Moment Coefficient (CM_alpha)
    % CM_alpha must be NEGATIVE for stability (CoP is forward of CoG).
    % Note: The paper provides a Torque Constant (tau*) of 0.308 Nm, which
    % relates to dynamic stability but is often incorporated into Cm and Cl.
    p_Cm = [-1.5, 0]; % Example: Cm = -1.5 * alpha (where alpha is in radians)
    
    % --- 4. Aerodynamic Coefficient Functions ---
    
    % The input alpha, beta are in RADIANS.
    
    aero.CD = @(alpha, beta) polyval(p_CD, abs(alpha));
    aero.CL = @(alpha, beta) polyval(p_CL, alpha);
    aero.Cm = @(alpha, beta) polyval(p_Cm, alpha);
    
    % --- CRITICAL COEFFICIENTS FOR STABILITY AND SPIRAL ---
    
    % CY (Side Force Coefficient) - MUST INCLUDE MAGNUS EFFECT
    % Magnus force (FY) is generated by the spin (px) and is perpendicular to
    % both the spin axis and the velocity vector.
    % CY_magnus = C_Y_p * (px * L / 2V) * alpha
    % C_Y_p is the Magnus force derivative, typically 0.05 to 0.2 for a football.
    % V is the air speed, px is the roll rate (spin rate)
    aero.CY = @(alpha, beta, V, px) 0.15 * (px * aero.L / (2*V)) * alpha; 
    % NOTE: This requires V and px (roll rate) as inputs!
    
    % Cl (Roll Moment Coefficient) - SPIN DAMPING
    % Cl is the rolling moment. It is dominated by the damping moment (Clp)
    % which slows the spin.
    % Cl = C_l_p * (px * L / 2V)
    % C_l_p (Spin damping derivative) is strongly negative.
    aero.Cl = @(alpha, beta, V, px) -0.05 * (px * aero.L / (2*V)); % Spin Damping
    % NOTE: This also requires V and px as inputs!
    
    % Cn (Yaw Moment Coefficient)
    % Yawing moment is zero due to symmetry, unless side-slip (beta) is used.
    aero.Cn = @(alpha, beta) 0*beta; % Neglecting Yaw-Magnus effect

    % Optional external force/moment
    aero.Fext = @(t) (t >= 1 && t <= 2) * [0; 0; 0];
    aero.Mext = @(t) (t >= 1 && t <= 1.1) * [0; 0; 0];
    % --- Initial State ---
    
    % Initialization based on "long bomb" paper
    initialization.launch_angle = 30; % in degrees from WAGNER
    initialization.v0 = [27.4*cosd(initialization.launch_angle) 0 27.4*sind(initialization.launch_angle)]; % initial velocity vector (u,v,w)_0
    initialization.omega0 = [62.8 0 0]; % initial rotational velocity vector (p,q,r)_0 (omega_spin = 62.8 rad/s)
    initialization.euler0 = [0, -initialization.launch_angle*pi/180, 0]; %[yaw pitch roll];   % [psi theta phi]
    initialization.quat0  = eul2quat(initialization.euler0);   % returns [w x y z]
    initialization.pos0 = [0 0 2]; % initial position in inertial frame
    initialization.tf = 100; %maximum simulation time
   
end
